env:
    node: true
    es2017: true
extends: eslint:recommended
rules:
    no-constant-condition:
        - error
        - checkLoops: false
    no-unused-vars:
        - error
        - varsIgnorePattern: ^_
          argsIgnorePattern: ^_
