extends: eslint:recommended

env:
  node: true
  es2017: true

parserOptions:
  ecmaVersion: 2018

rules:
  no-constant-condition:
    - error
    - checkLoops: false
  no-unused-vars:
    - error
    - varsIgnorePattern: ^_
      argsIgnorePattern: ^_
